name: Build React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18' # or any version your app uses

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
      # if you want to download the file from the artifact section run this task otherwise remove it 
      - name: Upload build folder
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build
